# Generated by Django 6.0.7 on 2026-08-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_roll_number_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
