# Generated by Django 6.0.7 on 2026-08-02 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_attendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='staus',
        ),
    ]
