# Generated by Django 6.0.7 on 2026-08-02 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_attendence_staus'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
