# Generated by Django 6.0.7 on 2026-08-02 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_attendence_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
