# Generated by Django 6.0.7 on 2026-08-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_notice_date_notice_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
