# Generated by Django 6.0.7 on 2026-08-05 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_teacher_course_alter_student_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
    ]
