# Generated by Django 6.0.7 on 2026-08-12 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_teacher_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendence',
            name='status',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='student',
        ),
        migrations.AddField(
            model_name='attendence',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.student'),
        ),
    ]
