# Generated by Django 6.0.7 on 2026-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_attendence_status_remove_attendence_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence',
            name='status',
            field=models.CharField(blank=True, null=True),
        ),
    ]
